
# Linear Algebra


In [2]:
import numpy as np

<H1> Vector Operations </H1> 

In [3]:
u = np.array([2,4,5,6])

In [4]:
u

array([2, 4, 5, 6])

In [5]:
v = np.array([1,0,0,2])

In [6]:
v

array([1, 0, 0, 2])

In [7]:
u + v

array([3, 4, 5, 8])

In [8]:
u * v

array([ 2,  0,  0, 12])

<H1> Multiplication </H1>