
# Numpy Fundamentals for Machine Learning

This notebook covers fundamental NumPy operations including array creation.


In [1]:
import numpy as np


# Creating Arrays



<b> </b>

In [2]:
np.zeros(10) #initialize weight vector for 10 features

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(8) #initialize weight vector of size 8(one parameter per feature)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.5) #initialize bias vector with constant value(baseline offset)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,2,3,4,5,6,7,8]) #construct design matrix with shape(1,8)--->(n_samples,n_features)

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
a[2]

np.int64(3)

In [8]:
a[2] =120801

In [9]:
a

array([     1,      2, 120801,      4,      5,      6,      7,      8])

In [10]:
np.linspace(0,1,11) #Creates a fixed number of equally spaced points over a specified interval 
                    # — commonly used for plotting, simulations, 
                    #or generating smooth input ranges in ML experiments

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [11]:
np.eye(10,M=None,k=0,dtype=float) # identity matrix used for regularization (e.g., X^T X + λI)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(0,1,10) #empty tensor with shape (0, 1, 10) sampled from Uniform(0,1)

array([], shape=(0, 1, 10), dtype=float64)

In [13]:
b= np.random.rand() 

In [14]:
b

0.718456517754606

In [15]:
np.random.randn(1,2) # weight matrix (n_outputs, n_features) initialized from N(0,1)

array([[-0.66782983, -0.26079603]])

In [16]:
c = np.arange(0,30,dtype = float)

In [17]:
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.])

In [18]:
c.reshape(10,3) # convert to (n_samples, n_features) for sklearn

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]])

<H1>Multidimensional Array</H1>

<b>Creating 2D Array</b>

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

<b>Creating multidimensional array</b>

In [20]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
n[0] # Access the row

array([1, 2, 3])

In [23]:
n[:] #selects the full array and returns a view (not a copy) in NumPy.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
n[: ,1] #access the column

array([2, 5, 8])

In [25]:
n[: ,2]

array([3, 6, 9])

In [26]:
n[2] =[1,1,1] #inserting values at row 2

In [27]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [28]:
n[: ,2] = [0,1,2] #Inserting at column 2

In [29]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [1, 1, 2]])

<H1>Randomly generated Arrays</H1>

In [30]:
np.random.seed(2) #fixes the random generator
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [31]:
np.random.randint(low = 0,high = 100,size = (5,2))

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

<H1>Element wise Operations</H1>

<b1>element-wise operations mean applying a mathematical operation independently to every value in a vector, matrix, or tensor.Instead of treating the data as a single object, the operation happens position-by-position.(Add,Sub,Mul,Div)</b1>

In [32]:
E = np.arange(5)
E

array([0, 1, 2, 3, 4])

In [33]:
E+1

array([1, 2, 3, 4, 5])

In [34]:
E*2

array([0, 2, 4, 6, 8])

In [35]:
E/100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [36]:
F = 10+(E*2)**2/100
F

array([10.  , 10.04, 10.16, 10.36, 10.64])

<H1>Summarizing Operations</H1>

<b1>Summarizing operations compute aggregate statistics from data, helping models analyze distributions, scale features, and evaluate performance.operations (like min, max, mean,standard deviation) reduce data into meaningful statistics that describe its overall behavior.They are called reduction operations because they reduce many values into fewer values.</b1>

In [37]:
F.min()

np.float64(10.0)

In [38]:
F.max()

np.float64(10.64)

In [39]:
F.sum()

np.float64(51.2)

In [40]:
F.mean()

np.float64(10.24)

In [41]:
F.std()

np.float64(0.2359660992600423)